image: alpine:latest

pages:
  stage: deploy
  script:
    - echo 'Nothing to do...'
  script:
    - mkdir .public
    - cd .public
    - ln -sf ../* .
    - cd ..
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
