image: alpine:latest

pages:
  stage: deploy
  script:
    - echo 'Nothing to do...'
  script:
    - mkdir .public
    - cp -r animations backgrounds codes css figures font fonts images js lanlep logos index.html sitemap* .public
    - cd .public
    - sed 's/href=\"papers\//href=\"https:\/\/gitlab.com\/monty\/monty.gitlab.io\/raw\/master\/papers\//' index.html | sed 's/href=\"presentations\//href=\"https:\/\/gitlab.com\/monty\/monty.gitlab.io\/raw\/master\/presentations\//' | sed 's/href=\"reports\//href=\"https:\/\/gitlab.com\/monty\/monty.gitlab.io\/raw\/master\/reports\//' > index2.html
    - mv index2.html index.html
    - cd ..
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
